# ===============================
# Render内部ネットワーク専用設定（IPブロックを完全スルー）
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d72lhps50q8c738t2rs0-a/galaxy_db_xwki
spring.datasource.username=galaxy_user
spring.datasource.password=CKDbZGpj1JRrYVOAa47qgmxiukmep0af
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate 設定
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect